# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough","smart","with_toc_data"]
highlighter:         pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            ANAND MANI SANKAR
tagline:          "thoughts.toString( )"
description:      'Ramblings and opinionated thoughts on technology.'
url:              http://anandmanisankar.com
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'Anand Mani Sankar'
  url:            https://twitter.com/msanand

# Custom vars
version:          1.3.0

github:
  repo:           https://github.com/msanand/msanand.github.io
